### ISSUE TITLE
Connecting...

### ISSUE THREAD

**Issue by hudson-dev** [project-sparthan/sparthan-myo#3]
The myo_print example just keep saying "Connecting..." Is there anything special I need to do with my ESP32 or Myo armband? I've already installed the ESP32 arduino library and the sparthan myo library. I've also connected the myo armband to my computer with the cyan bluetooth module and installed Myo Connect, I'm not sure if there is anything else I should be doing to get the armband to connect.

**Comment by bbrr132** [comment]
Hi, you should not be connecting the Bluetooth module to the armband. Instead, let it connect to the ESP32 directly.

**Comment by hexdae** [comment]
Closing this issue as solved
